version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=wp-test
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
  ws_br:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - "VIRTUAL_HOST=buscorepublica.me.dev"
      - "VIRTUAL_PORT=3000"
    volumes:
      - .:/ws-brepublica
    ports:
      - "3000:3000"
    depends_on:
      - db